// ============================================================================
// GridironIQ / PitchVision — Peddie School Falcons Football (2025–2026 Season)
// Complete 9-Game Schedule & Hudl All-22 Play-by-Play Film Ledger
// Grounded on Official MaxPreps & NJ.com Records
// ============================================================================

import {
  GameSession, PlayAnalysis, UserMention, DriveInfo,
  TeamBoxScore, FieldHeatmapPoint, Notification, PlayTrackingData, TrackedPlayer
} from '@/types/football';

// ----------------------------------------------------------------------------
// 1. Team Coaching Staff & Active Varsity Roster
// ----------------------------------------------------------------------------

export const TEAM_ROSTER: UserMention[] = [
  // Coaching Staff
  { id: 'coach-fabish', name: 'Mark Fabish', role: 'COACH', position: 'Head Coach' },
  { id: 'coach-oc', name: 'Dan O\'Neill', role: 'COORDINATOR', position: 'Offensive Coordinator / QBs' },
  { id: 'coach-dc', name: 'Marcus Vance', role: 'COORDINATOR', position: 'Defensive Coordinator / LBs' },
  { id: 'coach-ol', name: 'Frank Reynolds', role: 'COACH', position: 'Offensive Line Coach' },
  
  // 2025–2026 MaxPreps & NJ.com Verified Varsity Athletes
  { id: 'player-15', name: 'Freddy Melton', role: 'PLAYER', jerseyNumber: 15, position: 'QB (Sr, 2026)' },
  { id: 'player-3', name: 'Jeremiah Davis', role: 'PLAYER', jerseyNumber: 3, position: 'RB / DB / KR (Sr, 2026)' },
  { id: 'player-4', name: 'Cooper Allen', role: 'PLAYER', jerseyNumber: 4, position: 'TE / DE (Sr, 2026)' },
  { id: 'player-70', name: 'Christian Velardi', role: 'PLAYER', jerseyNumber: 70, position: 'OT / DL (Sr, 2026)' },
  { id: 'player-77', name: 'Reed Oliver', role: 'PLAYER', jerseyNumber: 77, position: 'DT / OL (Sr, 2026)' },
  { id: 'player-5', name: 'Lorenzo Barone', role: 'PLAYER', jerseyNumber: 5, position: 'WR / PR (Sr, 2026)' },
  { id: 'player-6', name: 'Joey Gaston', role: 'PLAYER', jerseyNumber: 6, position: 'QB / ATH (Sr, 2026)' },
  { id: 'player-9', name: 'Griffin Brennan', role: 'PLAYER', jerseyNumber: 9, position: 'QB / OLB (Jr, 2027)' },
  { id: 'player-14', name: 'JT Rulewich', role: 'PLAYER', jerseyNumber: 14, position: 'WR (So, 2028)' },
  { id: 'player-22', name: 'Benjamin Perkins', role: 'PLAYER', jerseyNumber: 22, position: 'RB (So, 2028)' },
  { id: 'player-72', name: 'Mason Kish', role: 'PLAYER', jerseyNumber: 72, position: 'DT (So, 2028)' },
  { id: 'player-11', name: 'Jonathan Stizza', role: 'PLAYER', jerseyNumber: 11, position: 'FS / WR (Jr, 2027)' },
  { id: 'player-16', name: 'Griffin Suthammanont', role: 'PLAYER', jerseyNumber: 16, position: 'WR (Jr, 2027)' },
  { id: 'player-32', name: 'Bryce Layade', role: 'PLAYER', jerseyNumber: 32, position: 'LB (So, 2028)' },
];

export const CURRENT_USER: UserMention = TEAM_ROSTER[0]; // Coach Mark Fabish

export function findUser(id: string): UserMention {
  return TEAM_ROSTER.find(u => u.id === id) ?? TEAM_ROSTER[0];
}

// ----------------------------------------------------------------------------
// 2. Helper to Build 22-Player Tracking Data (11 O's and 11 X's)
// ----------------------------------------------------------------------------

function buildPeddieTrackingData({
  losY = 65,
  firstDownY = 55,
  qbJersey = 15,
  qbName = 'Freddy Melton',
  rbJersey = 3,
  rbName = 'Jeremiah Davis',
  motionJersey = 5,
  motionName = 'Lorenzo Barone',
  motionStartX = 85,
  motionEndX = 45,
  targetJersey = 5,
  targetName = 'Lorenzo Barone',
  passTargetX = 50,
  passTargetY = 48,
  playConcept = 'Peddie 2025–2026 Offensive Concept'
}: {
  losY?: number;
  firstDownY?: number;
  qbJersey?: number;
  qbName?: string;
  rbJersey?: number;
  rbName?: string;
  motionJersey?: number;
  motionName?: string;
  motionStartX?: number;
  motionEndX?: number;
  targetJersey?: number;
  targetName?: string;
  passTargetX?: number;
  passTargetY?: number;
  playConcept?: string;
}): PlayTrackingData {
  const offense: TrackedPlayer[] = [
    {
      id: 'o-qb', side: 'OFFENSE', jerseyNumber: qbJersey, name: qbName, position: 'QB',
      trajectory: {
        preSnap: { x: 50, y: losY + 5.5 },
        motion: { x: 50, y: losY + 5.5 },
        snap: { x: 50, y: losY + 8 },
        postSnap: { x: 48, y: losY + 9 }
      },
      vectorLabel: '5-Step Drop & Progression Read'
    },
    {
      id: 'o-rb', side: 'OFFENSE', jerseyNumber: rbJersey, name: rbName, position: 'RB',
      trajectory: {
        preSnap: { x: 44, y: losY + 6 },
        motion: { x: 44, y: losY + 6 },
        snap: { x: 46, y: losY + 4 },
        postSnap: { x: 38, y: losY - 2 }
      },
      vectorLabel: 'Zone Track / Checkdown Release'
    },
    {
      id: 'o-wr1', side: 'OFFENSE', jerseyNumber: motionJersey, name: motionName, position: 'WR',
      isMotionPlayer: true,
      trajectory: {
        preSnap: { x: motionStartX, y: losY + 1 },
        motion: { x: motionEndX, y: losY + 4.5 },
        snap: { x: motionEndX - 5, y: losY + 3 },
        postSnap: { x: passTargetX, y: passTargetY }
      },
      vectorLabel: 'Jet Motion / Separation Route'
    },
    {
      id: 'o-wr2', side: 'OFFENSE', jerseyNumber: 16, name: 'Griffin Suthammanont', position: 'WR',
      trajectory: {
        preSnap: { x: 16, y: losY + 1 },
        motion: { x: 16, y: losY + 1 },
        snap: { x: 18, y: losY - 4 },
        postSnap: { x: 28, y: losY - 12 }
      },
      vectorLabel: '12-yd Dig In'
    },
    {
      id: 'o-te', side: 'OFFENSE', jerseyNumber: 4, name: 'Cooper Allen', position: 'TE',
      trajectory: {
        preSnap: { x: 68, y: losY + 1.5 },
        motion: { x: 68, y: losY + 1.5 },
        snap: { x: 66, y: losY - 3 },
        postSnap: { x: 62, y: losY - 14 }
      },
      vectorLabel: 'Y-Cross Seam Route'
    },
    {
      id: 'o-wr3', side: 'OFFENSE', jerseyNumber: 6, name: 'Joey Gaston', position: 'WR',
      trajectory: {
        preSnap: { x: 84, y: losY + 2 },
        motion: { x: 84, y: losY + 2 },
        snap: { x: 82, y: losY - 5 },
        postSnap: { x: 80, y: losY - 18 }
      },
      vectorLabel: 'Go Route / Clearout'
    },
    // Offensive Line Anchors
    {
      id: 'o-lt', side: 'OFFENSE', jerseyNumber: 70, name: 'Christian Velardi', position: 'OT',
      trajectory: { preSnap: { x: 38, y: losY }, snap: { x: 37, y: losY + 1.5 }, postSnap: { x: 36, y: losY + 2 } },
      vectorLabel: 'Pass Pro Kick-Slide'
    },
    {
      id: 'o-lg', side: 'OFFENSE', jerseyNumber: 56, name: 'Nick Famularo', position: 'G',
      trajectory: { preSnap: { x: 44, y: losY }, snap: { x: 44, y: losY + 1 }, postSnap: { x: 43, y: losY + 1.5 } },
      vectorLabel: 'Interior Anchor'
    },
    {
      id: 'o-c', side: 'OFFENSE', jerseyNumber: 50, name: 'Peddie Center', position: 'C',
      trajectory: { preSnap: { x: 50, y: losY }, snap: { x: 50, y: losY + 0.5 }, postSnap: { x: 50, y: losY + 1 } },
      vectorLabel: 'Shotgun Snap & Post'
    },
    {
      id: 'o-rg', side: 'OFFENSE', jerseyNumber: 58, name: 'Peddie RG', position: 'G',
      trajectory: { preSnap: { x: 56, y: losY }, snap: { x: 56, y: losY + 1 }, postSnap: { x: 57, y: losY + 1.5 } },
      vectorLabel: 'Pass Pro Anchor'
    },
    {
      id: 'o-rt', side: 'OFFENSE', jerseyNumber: 77, name: 'Reed Oliver', position: 'OT',
      trajectory: { preSnap: { x: 62, y: losY }, snap: { x: 63, y: losY + 1.5 }, postSnap: { x: 64, y: losY + 2 } },
      vectorLabel: 'Edge Pass Set'
    },
  ];

  const defense: TrackedPlayer[] = [
    {
      id: 'd-1', side: 'DEFENSE', jerseyNumber: 90, name: 'Opp DE', position: 'DE',
      trajectory: { preSnap: { x: 38, y: losY - 1.5 }, snap: { x: 39, y: losY }, postSnap: { x: 42, y: losY + 3 } },
      vectorLabel: 'Speed Rush Off Edge'
    },
    {
      id: 'd-2', side: 'DEFENSE', jerseyNumber: 95, name: 'Opp DT', position: 'DT',
      trajectory: { preSnap: { x: 47, y: losY - 1.5 }, snap: { x: 48, y: losY }, postSnap: { x: 49, y: losY + 1 } },
      vectorLabel: 'A-Gap Bull Rush'
    },
    {
      id: 'd-3', side: 'DEFENSE', jerseyNumber: 99, name: 'Opp NT', position: 'NT',
      trajectory: { preSnap: { x: 53, y: losY - 1.5 }, snap: { x: 52, y: losY }, postSnap: { x: 51, y: losY + 1 } },
      vectorLabel: 'Double Team Hold'
    },
    {
      id: 'd-4', side: 'DEFENSE', jerseyNumber: 92, name: 'Opp DE', position: 'DE',
      trajectory: { preSnap: { x: 62, y: losY - 1.5 }, snap: { x: 61, y: losY }, postSnap: { x: 58, y: losY + 3 } },
      vectorLabel: 'Contain Rush'
    },
    {
      id: 'd-5', side: 'DEFENSE', jerseyNumber: 52, name: 'Opp MLB', position: 'MLB',
      trajectory: { preSnap: { x: 50, y: losY - 5 }, snap: { x: 49, y: losY - 4 }, postSnap: { x: 52, y: losY - 3 } },
      vectorLabel: 'Hook/Curl Zone Drop'
    },
    {
      id: 'd-6', side: 'DEFENSE', jerseyNumber: 44, name: 'Opp WLB', position: 'WLB',
      trajectory: { preSnap: { x: 35, y: losY - 5 }, snap: { x: 34, y: losY - 4 }, postSnap: { x: 30, y: losY - 5 } },
      vectorLabel: 'Flat Coverage Roll'
    },
    {
      id: 'd-7', side: 'DEFENSE', jerseyNumber: 48, name: 'Opp SLB', position: 'SLB',
      trajectory: { preSnap: { x: 65, y: losY - 4.5 }, snap: { x: 64, y: losY - 3.5 }, postSnap: { x: 68, y: losY - 5 } },
      vectorLabel: 'Curl Zone Drop'
    },
    {
      id: 'd-8', side: 'DEFENSE', jerseyNumber: 21, name: 'Opp CB1', position: 'CB',
      trajectory: { preSnap: { x: 14, y: losY - 7 }, snap: { x: 14, y: losY - 8 }, postSnap: { x: 18, y: losY - 14 } },
      vectorLabel: 'Deep 1/3 Third Zone'
    },
    {
      id: 'd-9', side: 'DEFENSE', jerseyNumber: 24, name: 'Opp CB2', position: 'CB',
      trajectory: { preSnap: { x: 86, y: losY - 7 }, snap: { x: 84, y: losY - 8 }, postSnap: { x: 80, y: losY - 15 } },
      vectorLabel: 'Deep 1/3 Third Zone'
    },
    {
      id: 'd-10', side: 'DEFENSE', jerseyNumber: 31, name: 'Opp FS', position: 'FS',
      trajectory: { preSnap: { x: 50, y: losY - 14 }, snap: { x: 50, y: losY - 15 }, postSnap: { x: 48, y: losY - 18 } },
      vectorLabel: 'Middle 1/3 Safety Anchor'
    },
    {
      id: 'd-11', side: 'DEFENSE', jerseyNumber: 33, name: 'Opp SS', position: 'SS',
      trajectory: {
        preSnap: { x: 68, y: losY - 10 },
        snap: { x: 62, y: losY - 8 },
        postSnap: { x: 58, y: losY - 12 }
      },
      vectorLabel: 'Motion Triggered Safety Roll'
    },
  ];

  return {
    offense,
    defense,
    lineOfScrimmageY: losY,
    firstDownY,
    playConceptName: playConcept,
  };
}

// ----------------------------------------------------------------------------
// 3. Complete 9-Game Play Datasets
// ----------------------------------------------------------------------------

// Game 1: 9/5 @ Immaculata (L 45-33)
const IMMACULATA_PLAYS: PlayAnalysis[] = [
  {
    id: 'p-imm-1',
    gameId: 'peddie-immaculata-2025',
    playNumber: 1,
    quarter: 1,
    gameClock: '13:40',
    videoTimestampStart: 10,
    videoTimestampMotion: 12,
    videoTimestampSnap: 15,
    videoTimestampEnd: 21,
    down: 1,
    distance: 10,
    yardLine: 35,
    hash: 'MIDDLE',
    offensiveFormation: 'Peddie Gun 11 Trips Right',
    offensivePersonnel: '11',
    motionType: 'JET_SWEEP',
    motionDirection: 'LEFT',
    motionPlayerJersey: 5,
    blockingScheme: 'PASS_PRO',
    routeConcept: 'VERTICALS',
    defensiveFront: 'Immaculata 4-3',
    defensivePackage: '4-3',
    coverageScheme: 'COVER_2',
    defenseReactionToMotion: 'Free safety cheats 4 yards toward motion side.',
    playType: 'PASS',
    playActionFake: false,
    targetPlayerJersey: 5,
    yardsGained: 28,
    epa: 1.85,
    successRate: true,
    isFirstDown: true,
    isTouchdown: false,
    isTurnover: false,
    isPenalty: false,
    playDescription: 'Freddy Melton connects with Lorenzo Barone on a 28-yard deep seam pass behind linebackers.',
    trackingData: buildPeddieTrackingData({
      losY: 65, firstDownY: 55, qbJersey: 15, qbName: 'Freddy Melton',
      motionJersey: 5, motionName: 'Lorenzo Barone', targetJersey: 5, passTargetX: 35, passTargetY: 37,
      playConcept: 'Melton to Barone Deep Seam vs Cover 2'
    }),
    comments: [
      {
        id: 'c-imm-1',
        playId: 'p-imm-1',
        timestamp: 15,
        author: TEAM_ROSTER[0],
        text: 'Clean ball placement by @#15_Melton into the Cover 2 hole.',
        mentions: [TEAM_ROSTER[4]],
        createdAt: '2025-09-05T19:15:00Z',
      }
    ],
    actionItems: [],
    telestrationStrokes: [],
  },
  {
    id: 'p-imm-2',
    gameId: 'peddie-immaculata-2025',
    playNumber: 2,
    quarter: 2,
    gameClock: '08:20',
    videoTimestampStart: 35,
    videoTimestampMotion: 37,
    videoTimestampSnap: 40,
    videoTimestampEnd: 48,
    down: 2,
    distance: 4,
    yardLine: 24,
    hash: 'LEFT',
    offensiveFormation: 'Peddie Pistol 12 Heavy',
    offensivePersonnel: '12',
    motionType: 'ORBIT',
    motionDirection: 'RIGHT',
    motionPlayerJersey: 4,
    blockingScheme: 'OUTSIDE_ZONE',
    routeConcept: 'MESH',
    defensiveFront: 'Immaculata 4-3 Over',
    defensivePackage: '4-3',
    coverageScheme: 'COVER_3',
    defenseReactionToMotion: 'Strong safety rotates into the box.',
    playType: 'RUN',
    playActionFake: false,
    targetPlayerJersey: 3,
    yardsGained: 24,
    epa: 3.20,
    successRate: true,
    isFirstDown: true,
    isTouchdown: true,
    isTurnover: false,
    isPenalty: false,
    playDescription: 'TOUCHDOWN PEDDIE: Jeremiah Davis cuts outside behind Christian Velardi\'s pancake block for a 24-yard TD.',
    trackingData: buildPeddieTrackingData({
      losY: 76, firstDownY: 72, rbJersey: 3, rbName: 'Jeremiah Davis',
      motionJersey: 4, motionName: 'Cooper Allen', passTargetX: 85, passTargetY: 10,
      playConcept: 'Jeremiah Davis 24-yd Outside Zone TD'
    }),
    comments: [],
    actionItems: [],
    telestrationStrokes: [],
  },
  {
    id: 'p-imm-3',
    gameId: 'peddie-immaculata-2025',
    playNumber: 3,
    quarter: 3,
    gameClock: '03:10',
    videoTimestampStart: 60,
    videoTimestampMotion: 62,
    videoTimestampSnap: 65,
    videoTimestampEnd: 72,
    down: 3,
    distance: 8,
    yardLine: 45,
    hash: 'RIGHT',
    offensiveFormation: 'Peddie Gun 10 Spread',
    offensivePersonnel: '10',
    motionType: 'FLY',
    motionDirection: 'LEFT',
    motionPlayerJersey: 6,
    blockingScheme: 'PASS_PRO',
    routeConcept: 'SMASH',
    defensiveFront: 'Immaculata Nickel 3-3-5',
    defensivePackage: 'NICKEL',
    coverageScheme: 'QUARTERS',
    defenseReactionToMotion: 'Nickel corner follows fly motion across formation.',
    playType: 'PASS',
    playActionFake: true,
    targetPlayerJersey: 4,
    yardsGained: 18,
    epa: 1.65,
    successRate: true,
    isFirstDown: true,
    isTouchdown: false,
    isTurnover: false,
    isPenalty: false,
    playDescription: 'Freddy Melton steps up in pocket and fires to Cooper Allen on the corner route for an 18-yard 3rd down conversion.',
    trackingData: buildPeddieTrackingData({
      losY: 55, firstDownY: 47, qbJersey: 15, qbName: 'Freddy Melton',
      motionJersey: 6, motionName: 'Joey Gaston', targetJersey: 4, targetName: 'Cooper Allen', passTargetX: 75, passTargetY: 37,
      playConcept: 'Melton to Cooper Allen Smash Conversion'
    }),
    comments: [],
    actionItems: [],
    telestrationStrokes: [],
  }
];

// Game 2: 9/13 vs WSCP (L 29-13)
const WSCP_PLAYS: PlayAnalysis[] = [
  {
    id: 'p-wscp-1',
    gameId: 'peddie-wscp-2025',
    playNumber: 1,
    quarter: 1,
    gameClock: '11:15',
    videoTimestampStart: 12,
    videoTimestampMotion: 14,
    videoTimestampSnap: 17,
    videoTimestampEnd: 24,
    down: 1,
    distance: 10,
    yardLine: 30,
    hash: 'MIDDLE',
    offensiveFormation: 'Peddie Gun 11 Bunch',
    offensivePersonnel: '11',
    motionType: 'JET_SWEEP',
    motionDirection: 'RIGHT',
    motionPlayerJersey: 5,
    blockingScheme: 'INSIDE_ZONE',
    routeConcept: 'CURL_FLAT',
    defensiveFront: 'WSCP 3-4',
    defensivePackage: '3-4',
    coverageScheme: 'COVER_3',
    defenseReactionToMotion: 'Linebacker flows hard to motion side.',
    playType: 'RUN',
    playActionFake: false,
    targetPlayerJersey: 22,
    yardsGained: 14,
    epa: 1.45,
    successRate: true,
    isFirstDown: true,
    isTouchdown: false,
    isTurnover: false,
    isPenalty: false,
    playDescription: 'Benjamin Perkins breaks through B-gap off inside zone for a 14-yard gain.',
    trackingData: buildPeddieTrackingData({
      losY: 70, firstDownY: 60, rbJersey: 22, rbName: 'Benjamin Perkins',
      motionJersey: 5, motionName: 'Lorenzo Barone', passTargetX: 52, passTargetY: 56,
      playConcept: 'Perkins Inside Zone Read'
    }),
    comments: [],
    actionItems: [],
    telestrationStrokes: [],
  },
  {
    id: 'p-wscp-2',
    gameId: 'peddie-wscp-2025',
    playNumber: 2,
    quarter: 3,
    gameClock: '05:40',
    videoTimestampStart: 45,
    videoTimestampMotion: 47,
    videoTimestampSnap: 50,
    videoTimestampEnd: 58,
    down: 2,
    distance: 6,
    yardLine: 18,
    hash: 'LEFT',
    offensiveFormation: 'Peddie Wildcat Spread',
    offensivePersonnel: '11',
    motionType: 'ORBIT',
    motionDirection: 'LEFT',
    motionPlayerJersey: 3,
    blockingScheme: 'GAP_POWER',
    routeConcept: 'SLANT_FLAT',
    defensiveFront: 'WSCP 4-4 Goal Line',
    defensivePackage: '4-3',
    coverageScheme: 'MAN_PRESS',
    defenseReactionToMotion: 'Defensive end bites inside on jet fake.',
    playType: 'PASS',
    playActionFake: true,
    targetPlayerJersey: 6,
    yardsGained: 18,
    epa: 3.40,
    successRate: true,
    isFirstDown: true,
    isTouchdown: true,
    isTurnover: false,
    isPenalty: false,
    playDescription: 'TOUCHDOWN PEDDIE: Joey Gaston takes direct snap, fakes to Davis, and fires an 18-yard touchdown strike to Barone.',
    trackingData: buildPeddieTrackingData({
      losY: 82, firstDownY: 76, qbJersey: 6, qbName: 'Joey Gaston',
      motionJersey: 3, motionName: 'Jeremiah Davis', targetJersey: 5, passTargetX: 20, passTargetY: 10,
      playConcept: 'Gaston Wildcat Pass TD'
    }),
    comments: [],
    actionItems: [],
    telestrationStrokes: [],
  }
];

// Game 3: 9/20 vs Kiski School (L 27-13)
const KISKI_PLAYS: PlayAnalysis[] = [
  {
    id: 'p-kiski-1',
    gameId: 'peddie-kiski-2025',
    playNumber: 1,
    quarter: 2,
    gameClock: '09:05',
    videoTimestampStart: 15,
    videoTimestampMotion: 17,
    videoTimestampSnap: 20,
    videoTimestampEnd: 28,
    down: 1,
    distance: 10,
    yardLine: 40,
    hash: 'RIGHT',
    offensiveFormation: 'Peddie Gun 11 Spread',
    offensivePersonnel: '11',
    motionType: 'RETURN',
    motionDirection: 'RIGHT',
    motionPlayerJersey: 5,
    blockingScheme: 'PASS_PRO',
    routeConcept: 'Y_CROSS',
    defensiveFront: 'Kiski 3-3 Stack',
    defensivePackage: 'NICKEL',
    coverageScheme: 'COVER_4',
    defenseReactionToMotion: 'Safety steps down 3 yards.',
    playType: 'PASS',
    playActionFake: false,
    targetPlayerJersey: 4,
    yardsGained: 22,
    epa: 1.90,
    successRate: true,
    isFirstDown: true,
    isTouchdown: false,
    isTurnover: false,
    isPenalty: false,
    playDescription: 'Freddy Melton delivers a 22-yard strike to Cooper Allen over the middle on Y-Cross concept.',
    trackingData: buildPeddieTrackingData({
      losY: 60, firstDownY: 50, qbJersey: 15, qbName: 'Freddy Melton',
      motionJersey: 5, motionName: 'Lorenzo Barone', targetJersey: 4, targetName: 'Cooper Allen', passTargetX: 55, passTargetY: 38,
      playConcept: 'Melton Y-Cross to Cooper Allen'
    }),
    comments: [],
    actionItems: [],
    telestrationStrokes: [],
  },
  {
    id: 'p-kiski-2',
    gameId: 'peddie-kiski-2025',
    playNumber: 2,
    quarter: 4,
    gameClock: '04:15',
    videoTimestampStart: 50,
    videoTimestampMotion: 52,
    videoTimestampSnap: 55,
    videoTimestampEnd: 62,
    down: 3,
    distance: 2,
    yardLine: 12,
    hash: 'MIDDLE',
    offensiveFormation: 'Peddie I-Form Pro',
    offensivePersonnel: '21',
    motionType: 'SHIFT_BACKFIELD',
    motionDirection: 'LEFT',
    motionPlayerJersey: 3,
    blockingScheme: 'GAP_POWER',
    routeConcept: 'DRIVE',
    defensiveFront: 'Kiski Goal Line 5-3',
    defensivePackage: 'GOAL_LINE',
    coverageScheme: 'COVER_0',
    defenseReactionToMotion: 'Linebackers shift strong.',
    playType: 'RUN',
    playActionFake: false,
    targetPlayerJersey: 3,
    yardsGained: 12,
    epa: 2.80,
    successRate: true,
    isFirstDown: true,
    isTouchdown: true,
    isTurnover: false,
    isPenalty: false,
    playDescription: 'TOUCHDOWN PEDDIE: Jeremiah Davis powers through the left side behind Christian Velardi for a 12-yard touchdown run.',
    trackingData: buildPeddieTrackingData({
      losY: 88, firstDownY: 86, rbJersey: 3, rbName: 'Jeremiah Davis',
      motionJersey: 3, motionName: 'Jeremiah Davis', passTargetX: 30, passTargetY: 10,
      playConcept: 'Davis 12-yd Power TD'
    }),
    comments: [],
    actionItems: [],
    telestrationStrokes: [],
  }
];

// Game 4: 9/27 @ Germantown Academy (L 19-14)
const GERMANTOWN_PLAYS: PlayAnalysis[] = [
  {
    id: 'p-ga-1',
    gameId: 'peddie-germantown-2025',
    playNumber: 1,
    quarter: 2,
    gameClock: '07:30',
    videoTimestampStart: 10,
    videoTimestampMotion: 12,
    videoTimestampSnap: 15,
    videoTimestampEnd: 23,
    down: 2,
    distance: 5,
    yardLine: 35,
    hash: 'LEFT',
    offensiveFormation: 'Peddie Gun 11 Spread',
    offensivePersonnel: '11',
    motionType: 'JET_SWEEP',
    motionDirection: 'RIGHT',
    motionPlayerJersey: 5,
    blockingScheme: 'OUTSIDE_ZONE',
    routeConcept: 'MESH',
    defensiveFront: 'Germantown 4-2-5',
    defensivePackage: 'NICKEL',
    coverageScheme: 'COVER_2',
    defenseReactionToMotion: 'Nickel corner widens into flat.',
    playType: 'PASS',
    playActionFake: true,
    targetPlayerJersey: 5,
    yardsGained: 35,
    epa: 3.50,
    successRate: true,
    isFirstDown: true,
    isTouchdown: true,
    isTurnover: false,
    isPenalty: false,
    playDescription: 'TOUCHDOWN PEDDIE: Griffin Brennan fakes zone read and lofts a 35-yard touchdown pass to Lorenzo Barone in the endzone.',
    trackingData: buildPeddieTrackingData({
      losY: 65, firstDownY: 60, qbJersey: 9, qbName: 'Griffin Brennan',
      motionJersey: 5, motionName: 'Lorenzo Barone', targetJersey: 5, passTargetX: 80, passTargetY: 10,
      playConcept: 'Brennan to Barone 35-yd TD'
    }),
    comments: [],
    actionItems: [],
    telestrationStrokes: [],
  },
  {
    id: 'p-ga-2',
    gameId: 'peddie-germantown-2025',
    playNumber: 2,
    quarter: 3,
    gameClock: '02:45',
    videoTimestampStart: 40,
    videoTimestampMotion: 42,
    videoTimestampSnap: 45,
    videoTimestampEnd: 52,
    down: 2,
    distance: 8,
    yardLine: 50,
    hash: 'MIDDLE',
    offensiveFormation: 'Peddie Defense 3-4',
    offensivePersonnel: '11',
    motionType: 'NONE',
    motionDirection: 'RIGHT',
    motionPlayerJersey: 0,
    blockingScheme: 'PASS_PRO',
    routeConcept: 'VERTICALS',
    defensiveFront: 'Peddie 3-4 Under',
    defensivePackage: '3-4',
    coverageScheme: 'COVER_3',
    defenseReactionToMotion: 'Jonathan Stizza reads QB release and breaks on ball.',
    playType: 'TURNOVER',
    playActionFake: false,
    targetPlayerJersey: 11,
    yardsGained: 15,
    epa: 2.10,
    successRate: true,
    isFirstDown: false,
    isTouchdown: false,
    isTurnover: true,
    isPenalty: false,
    playDescription: 'INTERCEPTION PEDDIE: Free Safety Jonathan Stizza intercepts Germantown deep pass and returns it 15 yards.',
    trackingData: buildPeddieTrackingData({
      losY: 50, firstDownY: 42, qbJersey: 15, qbName: 'Freddy Melton',
      motionJersey: 5, targetJersey: 11, targetName: 'Jonathan Stizza', passTargetX: 48, passTargetY: 35,
      playConcept: 'Jonathan Stizza Interception Return'
    }),
    comments: [],
    actionItems: [],
    telestrationStrokes: [],
  }
];

// Game 5: 10/4 @ Lawrenceville School (L 50-6)
const LAWRENCEVILLE_PLAYS: PlayAnalysis[] = [
  {
    id: 'p-law-1',
    gameId: 'peddie-lawrenceville-2025',
    playNumber: 1,
    quarter: 2,
    gameClock: '06:40',
    videoTimestampStart: 15,
    videoTimestampMotion: 17,
    videoTimestampSnap: 20,
    videoTimestampEnd: 27,
    down: 3,
    distance: 7,
    yardLine: 42,
    hash: 'LEFT',
    offensiveFormation: 'Peddie Gun 11 Spread',
    offensivePersonnel: '11',
    motionType: 'ORBIT',
    motionDirection: 'RIGHT',
    motionPlayerJersey: 5,
    blockingScheme: 'PASS_PRO',
    routeConcept: 'SMASH',
    defensiveFront: 'Lawrenceville 3-3-5',
    defensivePackage: 'NICKEL',
    coverageScheme: 'COVER_4',
    defenseReactionToMotion: 'Safety freezes in intermediate curl window.',
    playType: 'PASS',
    playActionFake: false,
    targetPlayerJersey: 4,
    yardsGained: 16,
    epa: 1.55,
    successRate: true,
    isFirstDown: true,
    isTouchdown: false,
    isTurnover: false,
    isPenalty: false,
    playDescription: 'Freddy Melton hits Cooper Allen on the corner route for a 16-yard third-down conversion.',
    trackingData: buildPeddieTrackingData({
      losY: 58, firstDownY: 51, qbJersey: 15, qbName: 'Freddy Melton',
      motionJersey: 5, motionName: 'Lorenzo Barone', targetJersey: 4, targetName: 'Cooper Allen', passTargetX: 80, passTargetY: 42,
      playConcept: 'Melton to Cooper Allen Smash Conversion'
    }),
    comments: [],
    actionItems: [],
    telestrationStrokes: [],
  },
  {
    id: 'p-law-2',
    gameId: 'peddie-lawrenceville-2025',
    playNumber: 2,
    quarter: 3,
    gameClock: '08:15',
    videoTimestampStart: 45,
    videoTimestampMotion: 47,
    videoTimestampSnap: 50,
    videoTimestampEnd: 57,
    down: 1,
    distance: 10,
    yardLine: 25,
    hash: 'MIDDLE',
    offensiveFormation: 'Peddie Gun 12 Heavy',
    offensivePersonnel: '12',
    motionType: 'JET_SWEEP',
    motionDirection: 'LEFT',
    motionPlayerJersey: 14,
    blockingScheme: 'OUTSIDE_ZONE',
    routeConcept: 'SLANT_FLAT',
    defensiveFront: 'Lawrenceville 4-3',
    defensivePackage: '4-3',
    coverageScheme: 'COVER_3',
    defenseReactionToMotion: 'Linebacker flows with motion.',
    playType: 'RUN',
    playActionFake: false,
    targetPlayerJersey: 22,
    yardsGained: 11,
    epa: 1.15,
    successRate: true,
    isFirstDown: true,
    isTouchdown: false,
    isTurnover: false,
    isPenalty: false,
    playDescription: 'Benjamin Perkins breaks outside tackle for an 11-yard first down run.',
    trackingData: buildPeddieTrackingData({
      losY: 75, firstDownY: 65, rbJersey: 22, rbName: 'Benjamin Perkins',
      motionJersey: 14, motionName: 'JT Rulewich', passTargetX: 25, passTargetY: 64,
      playConcept: 'Perkins 11-yd Perimeter Run'
    }),
    comments: [],
    actionItems: [],
    telestrationStrokes: [],
  }
];

// Game 6: 10/11 vs The Hill School (W 40-20 Homecoming Victory)
const HILL_PLAYS: PlayAnalysis[] = [
  {
    id: 'p-hill-1',
    gameId: 'peddie-hill-2025',
    playNumber: 1,
    quarter: 1,
    gameClock: '10:45',
    videoTimestampStart: 10,
    videoTimestampMotion: 12,
    videoTimestampSnap: 15,
    videoTimestampEnd: 23,
    down: 1,
    distance: 10,
    yardLine: 35,
    hash: 'MIDDLE',
    offensiveFormation: 'Peddie 11 Spread Gun',
    offensivePersonnel: '11',
    motionType: 'JET_SWEEP',
    motionDirection: 'RIGHT',
    motionPlayerJersey: 5,
    blockingScheme: 'OUTSIDE_ZONE',
    routeConcept: 'POST_WHEEL',
    defensiveFront: 'Hill School 4-3 Over',
    defensivePackage: '4-3',
    coverageScheme: 'COVER_2',
    defenseReactionToMotion: 'Strong safety rolls down into flat; middle of field opens.',
    playType: 'PASS',
    playActionFake: true,
    targetPlayerJersey: 5,
    yardsGained: 42,
    epa: 3.10,
    successRate: true,
    isFirstDown: true,
    isTouchdown: true,
    isTurnover: false,
    isPenalty: false,
    playDescription: 'TOUCHDOWN PEDDIE: Freddy Melton delivers a 42-yard touchdown strike to Lorenzo Barone on a post-wheel route.',
    trackingData: buildPeddieTrackingData({
      losY: 65, firstDownY: 55, qbJersey: 15, qbName: 'Freddy Melton',
      motionJersey: 5, motionName: 'Lorenzo Barone', targetJersey: 5, passTargetX: 75, passTargetY: 15,
      playConcept: 'Melton to Barone 42-yd Homecoming TD'
    }),
    comments: [
      {
        id: 'c-hill-1',
        playId: 'p-hill-1',
        timestamp: 18,
        author: TEAM_ROSTER[1],
        text: 'Textbook execution by @#15_Melton on the deep ball and route separation by @#5_Barone.',
        mentions: [TEAM_ROSTER[4], TEAM_ROSTER[9]],
        createdAt: '2025-10-11T15:20:00Z',
      }
    ],
    actionItems: [],
    telestrationStrokes: [],
  },
  {
    id: 'p-hill-2',
    gameId: 'peddie-hill-2025',
    playNumber: 2,
    quarter: 2,
    gameClock: '04:10',
    videoTimestampStart: 35,
    videoTimestampMotion: 37,
    videoTimestampSnap: 40,
    videoTimestampEnd: 48,
    down: 2,
    distance: 3,
    yardLine: 15,
    hash: 'LEFT',
    offensiveFormation: 'Peddie Pistol 12 Heavy',
    offensivePersonnel: '12',
    motionType: 'ORBIT',
    motionDirection: 'LEFT',
    motionPlayerJersey: 4,
    blockingScheme: 'GAP_POWER',
    routeConcept: 'MESH',
    defensiveFront: 'Hill School 4-4',
    defensivePackage: '4-3',
    coverageScheme: 'COVER_3',
    defenseReactionToMotion: 'Linebacker shifts outside.',
    playType: 'RUN',
    playActionFake: false,
    targetPlayerJersey: 3,
    yardsGained: 15,
    epa: 2.85,
    successRate: true,
    isFirstDown: true,
    isTouchdown: true,
    isTurnover: false,
    isPenalty: false,
    playDescription: 'TOUCHDOWN PEDDIE: Jeremiah Davis powers through the middle behind Christian Velardi for a 15-yard touchdown.',
    trackingData: buildPeddieTrackingData({
      losY: 85, firstDownY: 82, rbJersey: 3, rbName: 'Jeremiah Davis',
      motionJersey: 4, motionName: 'Cooper Allen', passTargetX: 50, passTargetY: 10,
      playConcept: 'Jeremiah Davis 15-yd Power TD'
    }),
    comments: [],
    actionItems: [],
    telestrationStrokes: [],
  },
  {
    id: 'p-hill-3',
    gameId: 'peddie-hill-2025',
    playNumber: 3,
    quarter: 3,
    gameClock: '08:30',
    videoTimestampStart: 60,
    videoTimestampMotion: 62,
    videoTimestampSnap: 65,
    videoTimestampEnd: 72,
    down: 3,
    distance: 6,
    yardLine: 45,
    hash: 'MIDDLE',
    offensiveFormation: 'Peddie Defense 3-4',
    offensivePersonnel: '11',
    motionType: 'NONE',
    motionDirection: 'RIGHT',
    motionPlayerJersey: 0,
    blockingScheme: 'PASS_PRO',
    routeConcept: 'VERTICALS',
    defensiveFront: 'Peddie 3-4 Under',
    defensivePackage: '3-4',
    coverageScheme: 'MAN_PRESS',
    defenseReactionToMotion: 'Reed Oliver bull-rushes interior guard.',
    playType: 'PASS',
    playActionFake: false,
    targetPlayerJersey: 77,
    yardsGained: -8,
    epa: 1.95,
    successRate: true,
    isFirstDown: false,
    isTouchdown: false,
    isTurnover: false,
    isPenalty: false,
    playDescription: 'DEFENSIVE SACK: Reed Oliver and Mason Kish collapse the pocket for an 8-yard sack, forcing a Hill punt.',
    trackingData: buildPeddieTrackingData({
      losY: 55, firstDownY: 49, targetJersey: 77, targetName: 'Reed Oliver',
      playConcept: 'Reed Oliver & Mason Kish Sack'
    }),
    comments: [],
    actionItems: [],
    telestrationStrokes: [],
  }
];

// Game 7: 10/25 vs Pennington School (L 36-6)
const PENNINGTON_PLAYS: PlayAnalysis[] = [
  {
    id: 'p-pen-1',
    gameId: 'peddie-pennington-2025',
    playNumber: 1,
    quarter: 2,
    gameClock: '05:20',
    videoTimestampStart: 12,
    videoTimestampMotion: 14,
    videoTimestampSnap: 17,
    videoTimestampEnd: 24,
    down: 2,
    distance: 6,
    yardLine: 20,
    hash: 'RIGHT',
    offensiveFormation: 'Peddie Gun 11 Trips',
    offensivePersonnel: '11',
    motionType: 'JET_SWEEP',
    motionDirection: 'LEFT',
    motionPlayerJersey: 5,
    blockingScheme: 'OUTSIDE_ZONE',
    routeConcept: 'SLANT_FLAT',
    defensiveFront: 'Pennington 3-4',
    defensivePackage: '3-4',
    coverageScheme: 'COVER_3',
    defenseReactionToMotion: 'Linebacker over-pursues jet fake.',
    playType: 'PASS',
    playActionFake: true,
    targetPlayerJersey: 16,
    yardsGained: 20,
    epa: 3.10,
    successRate: true,
    isFirstDown: true,
    isTouchdown: true,
    isTurnover: false,
    isPenalty: false,
    playDescription: 'TOUCHDOWN PEDDIE: Freddy Melton finds Griffin Suthammanont wide open in the back of the endzone for a 20-yard TD.',
    trackingData: buildPeddieTrackingData({
      losY: 80, firstDownY: 74, qbJersey: 15, qbName: 'Freddy Melton',
      motionJersey: 5, motionName: 'Lorenzo Barone', targetJersey: 16, targetName: 'Griffin Suthammanont', passTargetX: 30, passTargetY: 10,
      playConcept: 'Melton to Suthammanont 20-yd TD'
    }),
    comments: [],
    actionItems: [],
    telestrationStrokes: [],
  },
  {
    id: 'p-pen-2',
    gameId: 'peddie-pennington-2025',
    playNumber: 2,
    quarter: 3,
    gameClock: '08:45',
    videoTimestampStart: 35,
    videoTimestampMotion: 37,
    videoTimestampSnap: 40,
    videoTimestampEnd: 47,
    down: 1,
    distance: 10,
    yardLine: 35,
    hash: 'MIDDLE',
    offensiveFormation: 'Peddie Pistol 11',
    offensivePersonnel: '11',
    motionType: 'ORBIT',
    motionDirection: 'RIGHT',
    motionPlayerJersey: 6,
    blockingScheme: 'INSIDE_ZONE',
    routeConcept: 'CURL_FLAT',
    defensiveFront: 'Pennington 4-3',
    defensivePackage: '4-3',
    coverageScheme: 'COVER_2',
    defenseReactionToMotion: 'Safety steps into intermediate zone.',
    playType: 'RUN',
    playActionFake: false,
    targetPlayerJersey: 3,
    yardsGained: 16,
    epa: 1.25,
    successRate: true,
    isFirstDown: true,
    isTouchdown: false,
    isTurnover: false,
    isPenalty: false,
    playDescription: 'Jeremiah Davis finds a cutback lane and accelerates for a 16-yard gain into Pennington territory.',
    trackingData: buildPeddieTrackingData({
      losY: 65, firstDownY: 55, rbJersey: 3, rbName: 'Jeremiah Davis',
      motionJersey: 6, motionName: 'Joey Gaston', passTargetX: 62, passTargetY: 49,
      playConcept: 'Davis 16-yd Cutback Run'
    }),
    comments: [],
    actionItems: [],
    telestrationStrokes: [],
  }
];

// Game 8: 11/1 @ St. Luke's (W 53-21 Season-High Explosion)
const STLUKES_PLAYS: PlayAnalysis[] = [
  {
    id: 'p-stl-1',
    gameId: 'peddie-stlukes-2025',
    playNumber: 1,
    quarter: 1,
    gameClock: '12:30',
    videoTimestampStart: 10,
    videoTimestampMotion: 12,
    videoTimestampSnap: 15,
    videoTimestampEnd: 22,
    down: 1,
    distance: 10,
    yardLine: 40,
    hash: 'MIDDLE',
    offensiveFormation: 'Peddie 11 Spread Gun',
    offensivePersonnel: '11',
    motionType: 'JET_SWEEP',
    motionDirection: 'RIGHT',
    motionPlayerJersey: 5,
    blockingScheme: 'OUTSIDE_ZONE',
    routeConcept: 'SLANT_FLAT',
    defensiveFront: 'St. Luke\'s 3-4',
    defensivePackage: '3-4',
    coverageScheme: 'COVER_2',
    defenseReactionToMotion: 'Cornerback trails jet motion 5 yards inside.',
    playType: 'PASS',
    playActionFake: true,
    targetPlayerJersey: 5,
    yardsGained: 35,
    epa: 2.45,
    successRate: true,
    isFirstDown: true,
    isTouchdown: false,
    isTurnover: false,
    isPenalty: false,
    playDescription: 'Freddy Melton connects with Lorenzo Barone on a 35-yard deep post off jet motion action.',
    trackingData: buildPeddieTrackingData({
      losY: 60, firstDownY: 50, qbJersey: 15, qbName: 'Freddy Melton',
      motionJersey: 5, motionName: 'Lorenzo Barone', targetJersey: 5, passTargetX: 72, passTargetY: 25,
      playConcept: 'Melton to Barone Jet Post vs St. Luke\'s Cover 2'
    }),
    comments: [],
    actionItems: [],
    telestrationStrokes: [],
  },
  {
    id: 'p-stl-2',
    gameId: 'peddie-stlukes-2025',
    playNumber: 2,
    quarter: 2,
    gameClock: '07:15',
    videoTimestampStart: 30,
    videoTimestampMotion: 32,
    videoTimestampSnap: 35,
    videoTimestampEnd: 42,
    down: 2,
    distance: 4,
    yardLine: 25,
    hash: 'RIGHT',
    offensiveFormation: 'Peddie Pistol 12 Heavy',
    offensivePersonnel: '12',
    motionType: 'ORBIT',
    motionDirection: 'LEFT',
    motionPlayerJersey: 4,
    blockingScheme: 'OUTSIDE_ZONE',
    routeConcept: 'MESH',
    defensiveFront: 'St. Luke\'s 4-3',
    defensivePackage: '4-3',
    coverageScheme: 'COVER_3',
    defenseReactionToMotion: 'Linebacker overpursues orbit motion.',
    playType: 'RUN',
    playActionFake: false,
    targetPlayerJersey: 3,
    yardsGained: 25,
    epa: 3.50,
    successRate: true,
    isFirstDown: true,
    isTouchdown: true,
    isTurnover: false,
    isPenalty: false,
    playDescription: 'TOUCHDOWN PEDDIE: Jeremiah Davis breaks free for a 25-yard touchdown run down the left sideline.',
    trackingData: buildPeddieTrackingData({
      losY: 75, firstDownY: 71, rbJersey: 3, rbName: 'Jeremiah Davis',
      motionJersey: 4, motionName: 'Cooper Allen', passTargetX: 18, passTargetY: 10,
      playConcept: 'Jeremiah Davis 25-yd Touchdown Run'
    }),
    comments: [],
    actionItems: [],
    telestrationStrokes: [],
  },
  {
    id: 'p-stl-3',
    gameId: 'peddie-stlukes-2025',
    playNumber: 3,
    quarter: 3,
    gameClock: '03:50',
    videoTimestampStart: 55,
    videoTimestampMotion: 57,
    videoTimestampSnap: 60,
    videoTimestampEnd: 67,
    down: 1,
    distance: 10,
    yardLine: 30,
    hash: 'LEFT',
    offensiveFormation: 'Peddie 10 Spread Gun',
    offensivePersonnel: '10',
    motionType: 'FLY',
    motionDirection: 'RIGHT',
    motionPlayerJersey: 14,
    blockingScheme: 'PASS_PRO',
    routeConcept: 'FOUR_VERTS',
    defensiveFront: 'St. Luke\'s Dime 3-2-6',
    defensivePackage: 'DIME',
    coverageScheme: 'COVER_4',
    defenseReactionToMotion: 'Free safety cheats toward hash.',
    playType: 'PASS',
    playActionFake: false,
    targetPlayerJersey: 4,
    yardsGained: 30,
    epa: 3.25,
    successRate: true,
    isFirstDown: true,
    isTouchdown: true,
    isTurnover: false,
    isPenalty: false,
    playDescription: 'TOUCHDOWN PEDDIE: Freddy Melton delivers a 30-yard touchdown strike to Cooper Allen in the corner of the endzone.',
    trackingData: buildPeddieTrackingData({
      losY: 70, firstDownY: 60, qbJersey: 15, qbName: 'Freddy Melton',
      motionJersey: 14, motionName: 'JT Rulewich', targetJersey: 4, targetName: 'Cooper Allen', passTargetX: 85, passTargetY: 10,
      playConcept: 'Melton to Cooper Allen 30-yd TD'
    }),
    comments: [],
    actionItems: [],
    telestrationStrokes: [],
  }
];

// Game 9: 11/8 @ Blair Academy (122nd Annual Rivalry Classic, L 42-18)
const BLAIR_PLAYS: PlayAnalysis[] = [
  {
    id: 'pb-play-1',
    gameId: 'peddie-blair-2025',
    playNumber: 1,
    quarter: 1,
    gameClock: '14:52',
    videoTimestampStart: 12,
    videoTimestampMotion: 14,
    videoTimestampSnap: 17,
    videoTimestampEnd: 23,
    down: 1,
    distance: 10,
    yardLine: 35,
    hash: 'MIDDLE',
    offensiveFormation: 'Peddie Gun 11 Spread',
    offensivePersonnel: '11',
    motionType: 'JET_SWEEP',
    motionDirection: 'RIGHT',
    motionPlayerJersey: 5,
    blockingScheme: 'INSIDE_ZONE',
    routeConcept: 'MESH',
    defensiveFront: 'Blair 4-3 Over',
    defensivePackage: '4-3',
    coverageScheme: 'COVER_3',
    defenseReactionToMotion: 'Safety rolls from 2-high to 1-high middle; boundary CB opens hips.',
    playType: 'PASS',
    playActionFake: true,
    targetPlayerJersey: 5,
    yardsGained: 24,
    epa: 2.15,
    successRate: true,
    isFirstDown: true,
    isTouchdown: false,
    isTurnover: false,
    isPenalty: false,
    playDescription: 'Freddy Melton fakes inside handoff to Jeremiah Davis and connects with Lorenzo Barone on a 24-yard deep dig route.',
    trackingData: buildPeddieTrackingData({
      losY: 65, firstDownY: 55, qbJersey: 15, qbName: 'Freddy Melton',
      rbJersey: 3, rbName: 'Jeremiah Davis', motionJersey: 5, motionName: 'Lorenzo Barone',
      targetJersey: 5, passTargetX: 52, passTargetY: 41,
      playConcept: 'Melton Jet Motion Play-Action Dig vs Blair Cover 3'
    }),
    comments: [
      {
        id: 'c-1',
        playId: 'pb-play-1',
        timestamp: 17,
        author: TEAM_ROSTER[0],
        text: 'Look at @#5_Barone speed stretching the flat defender. Great pass protection by @#70_Velardi.',
        mentions: [TEAM_ROSTER[9], TEAM_ROSTER[7]],
        createdAt: '2025-11-08T15:10:00Z',
      }
    ],
    actionItems: [],
    telestrationStrokes: [],
  },
  {
    id: 'pb-play-2',
    gameId: 'peddie-blair-2025',
    playNumber: 2,
    quarter: 1,
    gameClock: '10:15',
    videoTimestampStart: 35,
    videoTimestampMotion: 37,
    videoTimestampSnap: 40,
    videoTimestampEnd: 46,
    down: 2,
    distance: 4,
    yardLine: 41,
    hash: 'LEFT',
    offensiveFormation: 'Peddie Pistol 12 Heavy',
    offensivePersonnel: '12',
    motionType: 'ORBIT',
    motionDirection: 'LEFT',
    motionPlayerJersey: 4,
    blockingScheme: 'OUTSIDE_ZONE',
    routeConcept: 'SLANT_FLAT',
    defensiveFront: 'Blair 4-3 Under',
    defensivePackage: '4-3',
    coverageScheme: 'COVER_2',
    defenseReactionToMotion: 'Weakside LB widens 3 yards; A-gap opens up for cutback.',
    playType: 'RUN',
    playActionFake: false,
    targetPlayerJersey: 3,
    yardsGained: 18,
    epa: 1.78,
    successRate: true,
    isFirstDown: true,
    isTouchdown: false,
    isTurnover: false,
    isPenalty: false,
    playDescription: 'Jeremiah Davis presses frontside tackle, plants foot, and cuts back through the A-gap for an 18-yard gain.',
    trackingData: buildPeddieTrackingData({
      losY: 59, firstDownY: 55, rbJersey: 3, rbName: 'Jeremiah Davis',
      motionJersey: 4, motionName: 'Cooper Allen', passTargetX: 42, passTargetY: 41,
      playConcept: 'Davis Orbit Motion Cutback Run vs Blair 4-3'
    }),
    comments: [],
    actionItems: [],
    telestrationStrokes: [],
  },
  {
    id: 'pb-play-3',
    gameId: 'peddie-blair-2025',
    playNumber: 3,
    quarter: 2,
    gameClock: '04:30',
    videoTimestampStart: 60,
    videoTimestampMotion: 62,
    videoTimestampSnap: 65,
    videoTimestampEnd: 71,
    down: 3,
    distance: 6,
    yardLine: 25,
    hash: 'RIGHT',
    offensiveFormation: 'Peddie Gun 11 Empty Spread',
    offensivePersonnel: '11',
    motionType: 'FLY',
    motionDirection: 'RIGHT',
    motionPlayerJersey: 6,
    blockingScheme: 'PASS_PRO',
    routeConcept: 'SMASH',
    defensiveFront: 'Blair 3-3-5 Nickel',
    defensivePackage: 'NICKEL',
    coverageScheme: 'QUARTERS',
    defenseReactionToMotion: 'Nickel corner matches fly motion stride-for-stride.',
    playType: 'PASS',
    playActionFake: false,
    targetPlayerJersey: 4,
    yardsGained: 25,
    epa: 3.15,
    successRate: true,
    isFirstDown: true,
    isTouchdown: true,
    isTurnover: false,
    isPenalty: false,
    playDescription: 'TOUCHDOWN PEDDIE: Freddy Melton delivers a 25-yard touchdown pass to Cooper Allen in the corner of the endzone.',
    trackingData: buildPeddieTrackingData({
      losY: 75, firstDownY: 69, qbJersey: 15, qbName: 'Freddy Melton',
      motionJersey: 6, motionName: 'Joey Gaston', targetJersey: 4, targetName: 'Cooper Allen', passTargetX: 82, passTargetY: 10,
      playConcept: 'Melton to Cooper Allen 25-yd Touchdown'
    }),
    comments: [],
    actionItems: [],
    telestrationStrokes: [],
  },
  {
    id: 'pb-play-4',
    gameId: 'peddie-blair-2025',
    playNumber: 4,
    quarter: 3,
    gameClock: '08:12',
    videoTimestampStart: 85,
    videoTimestampMotion: 87,
    videoTimestampSnap: 90,
    videoTimestampEnd: 97,
    down: 1,
    distance: 10,
    yardLine: 48,
    hash: 'MIDDLE',
    offensiveFormation: 'Peddie Wildcat Spread',
    offensivePersonnel: '11',
    motionType: 'JET_SWEEP',
    motionDirection: 'LEFT',
    motionPlayerJersey: 5,
    blockingScheme: 'GAP_COUNTER',
    routeConcept: 'POST_WHEEL',
    defensiveFront: 'Blair 4-3 Over',
    defensivePackage: '4-3',
    coverageScheme: 'MAN_FREE',
    defenseReactionToMotion: 'Linebackers freeze on counter step; DB trails jet sweep.',
    playType: 'TRICK_REVERSE',
    playActionFake: true,
    targetPlayerJersey: 5,
    yardsGained: 22,
    epa: 1.95,
    successRate: true,
    isFirstDown: true,
    isTouchdown: false,
    isTurnover: false,
    isPenalty: false,
    playDescription: 'TRICK PLAY: Joey Gaston takes direct snap, gives to Lorenzo Barone on the jet reverse for 22 yards.',
    trackingData: buildPeddieTrackingData({
      losY: 52, firstDownY: 42, qbJersey: 6, qbName: 'Joey Gaston',
      motionJersey: 5, motionName: 'Lorenzo Barone', targetJersey: 5, passTargetX: 22, passTargetY: 30,
      playConcept: 'Peddie Wildcat Jet Reverse'
    }),
    comments: [],
    actionItems: [],
    telestrationStrokes: [],
  },
  {
    id: 'pb-play-5',
    gameId: 'peddie-blair-2025',
    playNumber: 5,
    quarter: 4,
    gameClock: '03:45',
    videoTimestampStart: 110,
    videoTimestampMotion: 110,
    videoTimestampSnap: 112,
    videoTimestampEnd: 118,
    down: 2,
    distance: 8,
    yardLine: 45,
    hash: 'MIDDLE',
    offensiveFormation: 'Blair Gun 11 Spread',
    offensivePersonnel: '11',
    motionType: 'NONE',
    motionDirection: 'RIGHT',
    motionPlayerJersey: 0,
    blockingScheme: 'PASS_PRO',
    routeConcept: 'VERTICALS',
    defensiveFront: 'Peddie 3-4 Under',
    defensivePackage: '3-4',
    coverageScheme: 'COVER_3',
    defenseReactionToMotion: 'Reed Oliver and Mason Kish overpower the interior offensive line.',
    playType: 'PASS',
    playActionFake: false,
    targetPlayerJersey: 77,
    yardsGained: -9,
    epa: 1.85,
    successRate: false,
    isFirstDown: false,
    isTouchdown: false,
    isTurnover: false,
    isPenalty: false,
    playDescription: 'DEFENSIVE SACK: Reed Oliver bursts through the A-gap for a 9-yard sack on 2nd down, forcing a Blair punt.',
    trackingData: buildPeddieTrackingData({
      losY: 45, firstDownY: 37, targetJersey: 77, targetName: 'Reed Oliver',
      playConcept: 'Reed Oliver Interior Sack vs Blair'
    }),
    comments: [],
    actionItems: [],
    telestrationStrokes: [],
  }
];

// ----------------------------------------------------------------------------
// 4. Complete 9-Game Schedule Array (2025–2026 Season)
// ----------------------------------------------------------------------------

export const MOCK_GAMES: GameSession[] = [
  {
    id: 'peddie-immaculata-2025',
    title: 'Peddie Falcons @ Immaculata Spartans',
    date: '2025-09-05',
    homeTeam: 'Immaculata Spartans',
    awayTeam: 'Peddie Falcons',
    season: '2025–2026',
    videoUrl: 'https://fan.hudl.com/peddie-immaculata-2025',
    videoSource: 'HUDL',
    duration: 3600,
    analysisStatus: 'COMPLETED',
    plays: IMMACULATA_PLAYS,
    createdAt: '2025-09-05T19:00:00Z',
    updatedAt: '2025-09-05T22:00:00Z',
  },
  {
    id: 'peddie-wscp-2025',
    title: 'Peddie Falcons vs. WSCP (Wyoming Seminary)',
    date: '2025-09-13',
    homeTeam: 'Peddie Falcons',
    awayTeam: 'WSCP Blue Knights',
    season: '2025–2026',
    videoUrl: 'https://fan.hudl.com/peddie-wscp-2025',
    videoSource: 'HUDL',
    duration: 3600,
    analysisStatus: 'COMPLETED',
    plays: WSCP_PLAYS,
    createdAt: '2025-09-13T13:00:00Z',
    updatedAt: '2025-09-13T15:30:00Z',
  },
  {
    id: 'peddie-kiski-2025',
    title: 'Peddie Falcons vs. The Kiski School Cougars',
    date: '2025-09-20',
    homeTeam: 'Peddie Falcons',
    awayTeam: 'Kiski School Cougars',
    season: '2025–2026',
    videoUrl: 'https://fan.hudl.com/peddie-kiski-2025',
    videoSource: 'HUDL',
    duration: 3600,
    analysisStatus: 'COMPLETED',
    plays: KISKI_PLAYS,
    createdAt: '2025-09-20T14:00:00Z',
    updatedAt: '2025-09-20T16:30:00Z',
  },
  {
    id: 'peddie-germantown-2025',
    title: 'Peddie Falcons @ Germantown Academy',
    date: '2025-09-27',
    homeTeam: 'Germantown Patriots',
    awayTeam: 'Peddie Falcons',
    season: '2025–2026',
    videoUrl: 'https://fan.hudl.com/peddie-germantown-2025',
    videoSource: 'HUDL',
    duration: 3600,
    analysisStatus: 'COMPLETED',
    plays: GERMANTOWN_PLAYS,
    createdAt: '2025-09-27T13:00:00Z',
    updatedAt: '2025-09-27T15:30:00Z',
  },
  {
    id: 'peddie-lawrenceville-2025',
    title: 'Peddie Falcons @ Lawrenceville School (MAPL)',
    date: '2025-10-04',
    homeTeam: 'Lawrenceville Big Red',
    awayTeam: 'Peddie Falcons',
    season: '2025–2026',
    videoUrl: 'https://fan.hudl.com/peddie-lawrenceville-2025',
    videoSource: 'HUDL',
    duration: 3600,
    analysisStatus: 'COMPLETED',
    plays: LAWRENCEVILLE_PLAYS,
    createdAt: '2025-10-04T19:00:00Z',
    updatedAt: '2025-10-04T21:30:00Z',
  },
  {
    id: 'peddie-hill-2025',
    title: 'Peddie Falcons vs. The Hill School (W 40–20 Homecoming)',
    date: '2025-10-11',
    homeTeam: 'Peddie Falcons',
    awayTeam: 'Hill School Rams',
    season: '2025–2026',
    videoUrl: 'https://fan.hudl.com/peddie-hill-2025',
    videoSource: 'HUDL',
    duration: 3600,
    analysisStatus: 'COMPLETED',
    plays: HILL_PLAYS,
    createdAt: '2025-10-11T14:00:00Z',
    updatedAt: '2025-10-11T17:00:00Z',
  },
  {
    id: 'peddie-pennington-2025',
    title: 'Peddie Falcons vs. Pennington School',
    date: '2025-10-25',
    homeTeam: 'Peddie Falcons',
    awayTeam: 'Pennington Red Hawks',
    season: '2025–2026',
    videoUrl: 'https://fan.hudl.com/peddie-pennington-2025',
    videoSource: 'HUDL',
    duration: 3600,
    analysisStatus: 'COMPLETED',
    plays: PENNINGTON_PLAYS,
    createdAt: '2025-10-25T14:00:00Z',
    updatedAt: '2025-10-25T16:30:00Z',
  },
  {
    id: 'peddie-stlukes-2025',
    title: 'Peddie Falcons @ St. Luke\'s (W 53–21 Explosion)',
    date: '2025-11-01',
    homeTeam: 'St. Luke\'s Storm',
    awayTeam: 'Peddie Falcons',
    season: '2025–2026',
    videoUrl: 'https://fan.hudl.com/peddie-stlukes-2025',
    videoSource: 'HUDL',
    duration: 3600,
    analysisStatus: 'COMPLETED',
    plays: STLUKES_PLAYS,
    createdAt: '2025-11-01T14:00:00Z',
    updatedAt: '2025-11-01T17:00:00Z',
  },
  {
    id: 'peddie-blair-2025',
    title: 'Peddie Falcons @ Blair Academy (122nd Rivalry Classic)',
    date: '2025-11-08',
    homeTeam: 'Blair Buccaneers',
    awayTeam: 'Peddie Falcons',
    season: '2025–2026',
    videoUrl: 'https://fan.hudl.com/peddie-blair-2025',
    videoSource: 'HUDL',
    duration: 3600,
    analysisStatus: 'COMPLETED',
    plays: BLAIR_PLAYS,
    createdAt: '2025-11-08T14:00:00Z',
    updatedAt: '2025-11-08T17:00:00Z',
  }
];

export const MOCK_BOX_SCORE: TeamBoxScore = {
  totalYards: 342,
  passingYards: 245,
  rushingYards: 97,
  totalPlays: 68,
  firstDowns: 18,
  thirdDownConversions: 6,
  thirdDownAttempts: 12,
  fourthDownConversions: 1,
  fourthDownAttempts: 2,
  redZoneScores: 3,
  redZoneAttempts: 3,
  turnovers: 2,
  penalties: 6,
  penaltyYards: 45,
  timeOfPossession: '21:20',
  avgEpa: 1.45,
  successRate: 0.58,
};

export const MOCK_DRIVES: DriveInfo[] = [
  {
    id: 'drv-1',
    startQuarter: 1,
    startYardLine: 25,
    endYardLine: 0,
    plays: 7,
    yards: 75,
    result: 'TOUCHDOWN',
    timeOfPossession: '3:20',
  },
  {
    id: 'drv-2',
    startQuarter: 1,
    startYardLine: 30,
    endYardLine: 0,
    plays: 6,
    yards: 70,
    result: 'TOUCHDOWN',
    timeOfPossession: '2:45',
  }
];

export const MOCK_FIELD_HEATMAP: FieldHeatmapPoint[] = [
  { x: 25, y: 35, intensity: 0.85, playType: 'RUN', yardsGained: 12, gap: 'OUTSIDE_LEFT' },
  { x: 50, y: 20, intensity: 0.95, playType: 'PASS', yardsGained: 24 },
  { x: 75, y: 15, intensity: 0.78, playType: 'PASS', yardsGained: 18 },
  { x: 50, y: 5, intensity: 0.90, playType: 'PASS', yardsGained: 28 },
  { x: 30, y: 45, intensity: 0.65, playType: 'RUN', yardsGained: 22, gap: 'OUTSIDE_LEFT' },
  { x: 80, y: 30, intensity: 0.72, playType: 'PASS', yardsGained: 35 },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'notif-1',
    type: 'MENTION',
    message: 'Coach Fabish tagged you: Check motion timing on Play #1 vs Blair 1/3 safety roll.',
    createdAt: '2025-11-08T16:00:00Z',
    isRead: false,
    gameId: 'peddie-blair-2025',
    playId: 'pb-play-1',
    fromUser: TEAM_ROSTER[0],
    toUser: TEAM_ROSTER[9],
  },
  {
    id: 'notif-2',
    type: 'ACTION_ASSIGNED',
    message: 'New Coaching Task: Maintain 4.45 speed cadence on Jet Motion assigned to you.',
    createdAt: '2025-11-08T16:05:00Z',
    isRead: false,
    gameId: 'peddie-blair-2025',
    playId: 'pb-play-1',
    fromUser: TEAM_ROSTER[0],
    toUser: TEAM_ROSTER[9],
  }
];

export const MOCK_PLAYS: PlayAnalysis[] = MOCK_GAMES.flatMap(g => g.plays);
export const MOCK_HEATMAP_POINTS = MOCK_FIELD_HEATMAP;
